M48
; DRILL file {KiCad 9.0.6} date 2025-11-18T00:55:00+1000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-18T00:55:00+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X81.395Y-85.71
X86.245Y-85.71
T2
X81.095Y-82.68
X86.545Y-82.68
M30
